### ISSUE TITLE
Construir tela de configurações do aplicativo

### ISSUE THREAD

**Issue by cristianprochnow** [Higia-App/higia-mobile#16]
Aqui não precisa ser algo muito complexo nesse primeiro momento. Teremos apenas uma navegação básica, em que os botões de opção de configuração levarão para subtelas, onde realmente existirá o campo de configuração ou algo semelhante.

O esquema de página pode seguir exatamente o que está no protótipo, juntamente com as configurações que ali estão.

[Protótipo](https://www.figma.com/file/pa37YRxTBhzgeSWelJxjPT/Higia?type=design&node-id=28%3A172&mode=dev)

![image](https://github.com/Higia-App/higia-mobile/assets/48127848/105b677f-f1b1-405b-8b01-75cda414a7ad)

**Comment by guusdias** [comment]
Atualizamos os settings e deixamos sem o gradient no header, é preciso que seja verificado.
